# Generated by Django 3.1.12 on 2024-12-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
    ]
