# Generated by Django 3.1.12 on 2024-12-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20241215_2327'),
        ('tracker', '0004_auto_20241214_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
